Public Class Frm_ChartSal

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a SqlDataSource
        SqlDataSource2.Fill()
    End Sub

    Private Sub Frm_ChartSal_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub
End Class