Imports System.Data.OleDb
Imports DevExpress.XtraTreeList.Nodes
Public Class Frm_ChartOfAccount2
    Dim varbandincome, vattypeband, varbandbalancesheet, vattypeband2, varband_tdfkat, vattypeband3 As Integer
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard

        ' This line of code is generated by Data Source Configuration Wizard
        'Vw_treelistTableAdapter1.Fill(DB_InterpakDataSet31.vw_treelist)
    End Sub
    Dim VarLevel_No, VarLevel_No2, VarLevel_No3, VarNo_Serail As Integer
    Dim varcodetype, varmaxlevel As Integer
    Dim varlevel, varsavelevel1 As Integer
    Public Data As New DataTable

    Public Data2 As New DataTable


    Private Sub Frm_ChartofAccount3_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        On Error Resume Next


        Data.Columns.Add("Id")
        Data.Columns.Add("Name")
        Data.Columns.Add("Node_Id")

        rs = New ADODB.Recordset
        sql = "select  * from ST_CHARTOFACCOUNT  where Compny_Code = '" & VarCodeCompny & "'   order by Level_No ,No_Serail,Account_No   "
        rs = Cnn.Execute(sql)
        Do While Not rs.EOF


            If rs("Level_No").Value = 0 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), 0) 'المستوى الاول
            If rs("Level_No").Value = 1 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), rs("Level_No2").Value) 'المستوى الثانى
            If rs("Level_No").Value = 2 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), rs("Level_No2").Value) 'المستوى الثانى
            If rs("Level_No").Value = 3 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), rs("Level_No2").Value) 'المستوى الثانى
            If rs("Level_No").Value = 4 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), rs("Level_No2").Value) 'المستوى الثانى
            If rs("Level_No").Value = 5 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), rs("Level_No2").Value) 'المستوى الثانى
            If rs("Level_No").Value = 6 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value), rs("Level_No2").Value) 'المستوى الثانى




            rs.MoveNext()
        Loop
        rs.Close()


        Dim Node As TreeNode
        For Each Row As DataRow In Data.Rows
            Node = New TreeNode(Row("Name"))
            Node.Name = Row("Id")

            If Row("Node_Id") <> 0 Then
                TreeView1.Nodes.Find(Row("Node_Id"), True)(0).Nodes.Add(Node)
            Else
                TreeView1.Nodes.Add(Node)
            End If

        Next

        'TreeView1.ExpandAll()
        TreeView1.CollapseAll()



    End Sub

    Private Sub TreeView1_AfterSelect(sender As Object, e As TreeViewEventArgs) Handles TreeView1.AfterSelect

        select_Tree()

    End Sub


    Sub select_Tree()
        On Error Resume Next
        txt_AccountNo2.Text = ""
        txt_NameAccount2.Text = ""
        varsavelevel1 = 0
        '===================================Select Account
        sql = "    SELECT * FROM ST_CHARTOFACCOUNT WHERE  (AccountNo_Name = '" & Trim(TreeView1.SelectedNode.Text.ToString()) & "')  and Compny_Code = '" & VarCodeCompny & "' "
        rs3 = Cnn.Execute(sql)
        If rs3.EOF = False Then
            varlevel = rs3("Level_No").Value
            txt_AccountNo1.Text = Trim(rs3("Account_No").Value)
            VarLevel_No = Trim(rs3("Level_No2").Value)
            VarNo_Serail = Trim(rs3("NO_SERAIL").Value)
            txt_NameAccount1.Text = Trim(rs3("AccountName").Value)

            If Trim(rs3("AccountType").Value) = 0 Then Chek1.Checked = True
            If Trim(rs3("AccountType").Value) = 1 Then Chek2.Checked = True

            If Trim(rs3("AccountPh").Value) = 0 Then Chek3.Checked = True
            If Trim(rs3("AccountPh").Value) = 1 Then Chek4.Checked = True

        End If
        'If varlevel = 4 Then  Else txt_AccountNo2.Visible = True : txt_NameAccount2.Visible = True : LabelX1.Visible = True
        '==========================================================

        'sql = "  SELECT  Level_No2, MAX(Account_No) + 1 AS SumMaxLevel FROM ST_CHARTOFACCOUNT GROUP BY Level_No2" & _
        '" HAVING(Level_No2 = '" & VarNo_Serail & "') "
        If varlevel = 0 Then
            sql = "SELECT Level_No2, MAX(Account_No) + 1 AS SumMaxLevel, Level_No " & _
            " FROM     ST_CHARTOFACCOUNT " & _
            " where Compny_Code = '" & VarCodeCompny & "'  " & _
            " GROUP BY Level_No2, Level_No " & _
            " HAVING (Level_No2 = '" & txt_AccountNo1.Text & "') AND (Level_No = '" & 1 & "') "
        Else

            sql = "SELECT Level_No2, MAX(Account_No) + 1 AS SumMaxLevel, Level_No " & _
                      " FROM     ST_CHARTOFACCOUNT " & _
                      " where Compny_Code = '" & VarCodeCompny & "'  " & _
                      " GROUP BY Level_No2, Level_No " & _
                      " HAVING (Level_No2 = '" & VarNo_Serail & "')  "
        End If


        rs2 = Cnn.Execute(sql)
        If rs2.EOF = False Then
            txt_AccountNo2.Text = Trim(rs2("SumMaxLevel").Value)
            txt_AccountNo2.Visible = True : txt_NameAccount2.Visible = True : LabelX1.Visible = True

        Else
            If Len(Trim(VarNo_Serail)) = 8 Then txt_AccountNo2.Text = Trim(Str(VarNo_Serail)) + "01"
            If Len(Trim(VarNo_Serail)) = 6 Then txt_AccountNo2.Text = Trim(Str(VarNo_Serail)) + "01"
            If Len(Trim(VarNo_Serail)) = 3 Then txt_AccountNo2.Text = Trim(Str(VarNo_Serail)) + "001"
            If Len(Trim(VarNo_Serail)) = 1 Then txt_AccountNo2.Text = Trim(Str(VarNo_Serail)) + "01"
            If Len(Trim(VarNo_Serail)) = 10 Then txt_AccountNo2.Text = Trim(Str(VarNo_Serail)) + "01"
            If Len(Trim(VarNo_Serail)) = 9 Then txt_AccountNo2.Text = Trim(Str(VarNo_Serail)) + "01"

           

        End If
        If Len(Trim(txt_AccountNo1.Text)) = 11 Then
            LabelX1.Visible = False
            txt_AccountNo2.Visible = False
            txt_NameAccount2.Visible = False
        Else
            LabelX1.Visible = True
            txt_AccountNo2.Visible = True
            txt_NameAccount2.Visible = True
        End If

        txt_NameAccount2.Select()
    End Sub



    Sub save_tree()
        On Error Resume Next
        If Len(txt_NameAccount1.Text) = 0 Then MsgBox("من فضلك اختار الحساب  ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "ERP Solution Software Module") : Exit Sub

        If varsavelevel1 <> 1 Then
            If txt_NameAccount2.Text = "" Then MsgBox("من فضلك ادخل اسم الحساب", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRight, "ERP Solution Software Module") : Exit Sub
        End If

        If Len(Trim(txt_AccountNo2.Text)) = 8 Then VarLevel_No = 3
        If Len(Trim(txt_AccountNo2.Text)) = 9 Then VarLevel_No = 3
        If Len(Trim(txt_AccountNo2.Text)) = 6 Then VarLevel_No = 2
        If Len(Trim(txt_AccountNo2.Text)) = 3 Then VarLevel_No = 1
        If Len(Trim(txt_AccountNo2.Text)) = 1 Then VarLevel_No = 0
        If Len(Trim(txt_AccountNo2.Text)) = 10 Then VarLevel_No = 4
        If Len(Trim(txt_AccountNo2.Text)) = 11 Then VarLevel_No = 4



        If varsavelevel1 <> 1 Then
            sql = "INSERT INTO ST_CHARTOFACCOUNT (Level_No, No_Serail,Account_No,Level_No2,AccountName,AccountType,AccountPh,AccountNo_Name,Account_No_Update,Compny_Code) " & _
               " values  (N'" & VarLevel_No & "' ,N'" & txt_AccountNo2.Text & "',N'" & txt_AccountNo2.Text & "',N'" & txt_AccountNo1.Text & "',N'" & txt_NameAccount2.Text & "',N'" & 0 & "',N'" & 0 & "',N'" & txt_AccountNo2.Text + "-" + txt_NameAccount2.Text & "','" & txt_AccountNo2.Text & "','" & VarCodeCompny & "')"
            Cnn.Execute(sql)
            TreeView1.Nodes.Add(txt_AccountNo2.Text + "-" + txt_NameAccount2.Text)

            txt_NameAccount2.Text = ""
        Else
            sql = "INSERT INTO ST_CHARTOFACCOUNT (Level_No, No_Serail,Account_No,Level_No2,AccountName,AccountType,AccountPh,AccountNo_Name,Account_No_Update,Compny_Code) " & _
         " values  (N'" & 0 & "' ,N'" & txt_AccountNo1.Text & "',N'" & txt_AccountNo1.Text & "',N'" & txt_AccountNo1.Text & "',N'" & txt_NameAccount1.Text & "',N'" & 0 & "',N'" & 0 & "',N'" & txt_AccountNo1.Text + "-" + txt_NameAccount1.Text & "',N'" & txt_AccountNo1.Text & "','" & VarCodeCompny & "')"
            Cnn.Execute(sql)
            TreeView1.Nodes.Add(txt_AccountNo1.Text + "-" + txt_NameAccount1.Text)

            txt_NameAccount1.Text = ""
        End If



        MsgBox("Save Data ", MsgBoxStyle.Information + MsgBoxStyle.MsgBoxRight, "ERP Solution Software Module")

        'find_tree()
        'TreeView1.Refresh()
        'TreeView1.SelectedNode.Nodes.Add(txt_AccountNo1.Text + "-" + txt_NameAccount1.Text)



        'TreeView1.Nodes.Item("Node Name")



        'TreeView1.Nodes.Clear()
        'Find_Node()
    End Sub






    Sub find_tree()
        'On Error Resume Next

        'TreeView1.Nodes.RemoveAt()
        Dim Data2 As New DataTable
        Data2.Columns.Add("Id")
        Data2.Columns.Add("Name")
        Data2.Columns.Add("Node_Id")

        rs = New ADODB.Recordset
        sql = "select  * from ST_CHARTOFACCOUNT where Compny_Code = '" & VarCodeCompny & "'  order by Level_No ,No_Serail,Account_No      "
        rs = Cnn.Execute(sql)
        Do While Not rs.EOF


            If rs("Level_No").Value = 0 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value) + "-" + Trim(rs("Account_No").Value), 0) 'المستوى الاول
            If rs("Level_No").Value = 1 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value) + "-" + Trim(rs("Account_No").Value), rs("Level_No2").Value) 'المستوى الثانى
            If rs("Level_No").Value = 2 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value) + "-" + Trim(rs("Account_No").Value), rs("Level_No2").Value) 'المستوى الثالث
            If rs("Level_No").Value = 3 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value) + "-" + Trim(rs("Account_No").Value), rs("Level_No2").Value) 'المستوى الرابع
            If rs("Level_No").Value = 4 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value) + "-" + Trim(rs("Account_No").Value), rs("Level_No2").Value) 'المستوى الخامس
            If rs("Level_No").Value = 5 Then Data.Rows.Add(rs("Account_No").Value, Trim(rs("AccountNo_Name").Value) + "-" + Trim(rs("Account_No").Value), rs("Level_No2").Value) 'المستوى الخامس




            rs.MoveNext()
        Loop
        rs.Close()


        Dim Node As TreeNode
        For Each Row As DataRow In Data2.Rows
            Node = New TreeNode(Row("Name"))
            Node.Name = Row("Id")

            If Row("Node_Id") <> 0 Then
                TreeView1.Nodes.Find(Row("Node_Id"), True)(0).Nodes.Add(Node)
            Else
                TreeView1.Nodes.Add(Node)
            End If
            'TreeView1.Nodes.Add(Node)
        Next

        TreeView1.ExpandAll()
        'TreeView1.CollapseAll()
    End Sub

    Private Sub txt_NameAccount2_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txt_NameAccount2.KeyPress
        If e.KeyChar = Convert.ToChar(13) Then
            save_tree()
            select_Tree()
        End If
    End Sub
    


    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        'sql = " Select Account_No      FROM dbo.St_AccountLv3LinkCustomer     WHERE(Account_No = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات العملاء", MsgBoxStyle.Critical, "Css") : Exit Sub


        'sql = " Select Customer_AccountNo      FROM dbo.St_CustomerData     WHERE(Customer_AccountNo = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات العملاء", MsgBoxStyle.Critical, "Css") : Exit Sub

        'sql = " Select Supliser_AccountNo      FROM dbo.St_SuppliserData     WHERE(Supliser_AccountNo = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات الموردين", MsgBoxStyle.Critical, "Css") : Exit Sub





        save_tree()

        select_Tree()
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        'On Error Resume Next
        Dim VarType, VarType2 As Integer

        If Len(txt_NameAccount1.Text) = 0 Then MsgBox("من فضلك اختار الحساب المراد تعديلة ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "ERP Solution Software Module") : Exit Sub


        'sql = " Select Account_No      FROM dbo.St_AccountLv3LinkCustomer     WHERE(Account_No = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات العملاء", MsgBoxStyle.Critical, "Css") : Exit Sub

        'sql = " Select Customer_AccountNo      FROM dbo.St_CustomerData     WHERE(Customer_AccountNo = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات العملاء", MsgBoxStyle.Critical, "Css") : Exit Sub

        'sql = " Select Supliser_AccountNo      FROM dbo.St_SuppliserData     WHERE(Supliser_AccountNo = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات الموردين", MsgBoxStyle.Critical, "Css") : Exit Sub

        If Chek1.Checked = True Then VarType = 0
        If Chek2.Checked = True Then VarType = 1

        If Chek3.Checked = True Then VarType2 = 0
        If Chek4.Checked = True Then VarType2 = 1

        sql = "    update      ST_CHARTOFACCOUNT set  AccountType='" & VarType & "' ,accountph= '" & VarType2 & "' " & _
        " WHERE  (Account_No_Update LIKE '" & Trim(txt_AccountNo1.Text) & "%') and  Compny_Code = '" & VarCodeCompny & "'  "
        rs = Cnn.Execute(sql)


        sql = "UPDATE  ST_CHARTOFACCOUNT  SET AccountName = '" & txt_NameAccount1.Text & "',AccountNo_Name = '" & txt_AccountNo1.Text + "-" + txt_NameAccount1.Text & "'  WHERE Account_No = '" & txt_AccountNo1.Text & "' and Compny_Code = '" & VarCodeCompny & "'  "
        rs = Cnn.Execute(sql)
        MsgBox("تم التعديل", MsgBoxStyle.Information, "CSS Solution Software Module")
        'find_tree()
    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        On Error Resume Next
        If Len(txt_NameAccount1.Text) = 0 Then MsgBox("من فضلك اختار الحساب المراد حذفه ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "ERP Solution Software Module") : Exit Sub

        'sql = " SELECT        dbo.MovmentStatement.AccountNo FROM            dbo.MovmentStatement INNER JOIN" & _
        '               "  dbo.BD_POS_Setting ON dbo.MovmentStatement.AccountNo = dbo.BD_POS_Setting.wallet_Code     WHERE(Account_No = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لا يمكن حذف حساب مرتبط بقيد", MsgBoxStyle.Critical, "Css") : Exit Sub

        '        sql = "SELECT        dbo.MovmentStatement.AccountNo" & _
        '" FROM            dbo.MovmentStatement INNER JOIN" & _
        ' "                        dbo.ST_CHARTOFACCOUNT ON dbo.MovmentStatement.Compny_Code = dbo.ST_CHARTOFACCOUNT.Compny_Code AND dbo.MovmentStatement.AccountNo = dbo.ST_CHARTOFACCOUNT.Account_No" & _
        '  "   WHERE(Account_No = '" & txt_AccountNo1.Text & "')"
        '        rs = Cnn.Execute(sql)
        '        If rs.EOF = False Then MsgBox("لا يمكن حذف حساب مرتبط بقيد", MsgBoxStyle.Critical, "Css") : Exit Sub


        'sql = " Select Account_No      FROM dbo.St_AccountLv3LinkCustomer     WHERE(Account_No = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات العملاء", MsgBoxStyle.Critical, "Css") : Exit Sub

        'sql = " Select Customer_AccountNo      FROM dbo.St_CustomerData     WHERE(Customer_AccountNo = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات العملاء", MsgBoxStyle.Critical, "Css") : Exit Sub


        'sql = " Select Supliser_AccountNo      FROM dbo.St_SuppliserData     WHERE(Supliser_AccountNo = '" & txt_AccountNo1.Text & "')"
        'rs = Cnn.Execute(sql)
        'If rs.EOF = False Then MsgBox("لايمكن الاضافة او التعديل او الحذف الا من بيانات الموردين", MsgBoxStyle.Critical, "Css") : Exit Sub


        If varlevel = 2 Then
            sql = "select * from Vw_AllAccountBalane where level3 ='" & txt_AccountNo1.Text & "' and Account_No ='" & txt_AccountNo1.Text & "' "
            rs2 = Cnn.Execute(sql)
            If rs2.EOF = False Then MsgBox("الحساب يوجد ارقام حسابات بداخلة لايمكن الحذف", MsgBoxStyle.Critical, "CSS Solution Software Module") : Exit Sub
        End If

        If varlevel = 1 Then
            sql = "select * from Vw_AllAccountBalane where level2 ='" & txt_AccountNo1.Text & "' and level3 ='" & txt_AccountNo1.Text & "'"
            rs2 = Cnn.Execute(sql)
            If rs2.EOF = False Then MsgBox("الحساب يوجد ارقام حسابات بداخلة لايمكن الحذف", MsgBoxStyle.Critical, "CSS Solution Software Module") : Exit Sub
        End If


        If varlevel = 0 Then
            sql = "select * from Vw_AllAccountBalane where level1 ='" & txt_AccountNo1.Text & "' and level2 ='" & txt_AccountNo1.Text & "' "
            rs2 = Cnn.Execute(sql)
            If rs2.EOF = False Then MsgBox("الحساب يوجد ارقام حسابات بداخلة لايمكن الحذف", MsgBoxStyle.Critical, "CSS Solution Software Module") : Exit Sub
        End If

        '=================================حركة الحساب
        sql2 = "  Select AccountNo      FROM dbo.MovmentStatement WHERE        (AccountNo ='" & txt_AccountNo1.Text & "') and Compny_Code = '" & VarCodeCompny & "' "
        rs2 = Cnn.Execute(sql2)
        If rs2.EOF = False Then MsgBox("الحساب يوجد عليه حركة", MsgBoxStyle.Critical, "CSS Solution Software Module") : Exit Sub
        '==============================================

        Dim x As String
        x = MsgBox("هل تريد حذف الحساب", MsgBoxStyle.YesNo + MsgBoxStyle.Question + MsgBoxStyle.MsgBoxRight, "CSS Solution Software Module")

        Select Case x
            Case vbNo

            Case vbYes


                sql = "Delete ST_CHARTOFACCOUNT  WHERE Account_No = " & txt_AccountNo1.Text & "   "
                rs = Cnn.Execute(sql)

                MsgBox("تم الحذف", MsgBoxStyle.Information, "CSS Solution Software Module")

                TreeView1.SelectedNode.Remove()
                'find_tree()
        End Select
        'find_tree()
    End Sub

    Private Sub SimpleButton4_Click(sender As Object, e As EventArgs) Handles SimpleButton4.Click
        sql = " SELECT Level_No, MAX(Account_No) + 1 AS SumMaxLevel " & _
      " FROM    ST_CHARTOFACCOUNT " & _
      " where Compny_Code = '" & VarCodeCompny & "'  " & _
      " GROUP BY Level_No " & _
      " HAVING (Level_No = '0') "

        rs2 = Cnn.Execute(sql)
        If rs2.EOF = False Then
            txt_AccountNo1.Text = Trim(rs2("SumMaxLevel").Value)
            txt_AccountNo2.Visible = False : txt_NameAccount2.Visible = False : LabelX1.Visible = False
            txt_NameAccount1.Text = ""
            varsavelevel1 = 1
        Else
            txt_AccountNo1.Text = "1"
            txt_AccountNo2.Visible = False : txt_NameAccount2.Visible = False : LabelX1.Visible = False
            txt_NameAccount1.Text = ""
            varsavelevel1 = 1
        End If
    End Sub

    Private Sub SimpleButton5_Click(sender As Object, e As EventArgs) Handles SimpleButton5.Click
        TreeView1.ExpandAll()

    End Sub

    Private Sub SimpleButton7_Click(sender As Object, e As EventArgs) Handles SimpleButton7.Click
        TreeView1.CollapseAll()
    End Sub
    Sub Search()
        On Error Resume Next


        GridControl4.DataSource = Nothing
        GridView7.Columns.Clear()

        'Dim con As New OleDb.OleDbConnection
        'Dim ss As String
        'ss = " Provider=OraOLEDB.Oracle;Data Source=test;User Id=" & varusername2 & ";Password=" & varPassword & ";"
        'con.ConnectionString = ss
        Dim ss As String
        Dim con As New OleDb.OleDbConnection
        ss = "Provider=SQLOLEDB;Initial Catalog= " & DatabaseName & " ;Data Source=" & ServerName & ";" & _
               "User ID=" & varusername2 & " ;Password=" & varPassword & ";"
        con.ConnectionString = ss
        con.Open()


        '   sql = "     SELECT        TOP (100) PERCENT RTRIM(dbo.Vw_PrintChart.AccountName) AS Levelname1, RTRIM(dbo.ST_CHARTOFACCOUNT.AccountNo_Name) AS LeveName2, RTRIM(ST_CHARTOFACCOUNT_1.AccountNo_Name) AS LevelName3,  " & _
        '"                         RTRIM(ST_CHARTOFACCOUNT_2.AccountNo_Name) AS levelName4, RTRIM(ST_CHARTOFACCOUNT_3.AccountNo_Name) AS levelName5, iif(dbo.ST_CHARTOFACCOUNT.AccountType=1,'ميزانية','قائمة دخل') as type, iif(dbo.ST_CHARTOFACCOUNT.AccountPh=1,'دائن','مدين') as typeacc " & _
        '" FROM            dbo.Vw_PrintChart INNER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT ON dbo.Vw_PrintChart.Account_No_Update = dbo.ST_CHARTOFACCOUNT.Level_No2 INNER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT AS ST_CHARTOFACCOUNT_1 ON dbo.ST_CHARTOFACCOUNT.Account_No = ST_CHARTOFACCOUNT_1.Level_No2 LEFT OUTER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT AS ST_CHARTOFACCOUNT_2 ON ST_CHARTOFACCOUNT_1.Account_No = ST_CHARTOFACCOUNT_2.Level_No2 LEFT OUTER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT AS ST_CHARTOFACCOUNT_3 ON ST_CHARTOFACCOUNT_2.Account_No = ST_CHARTOFACCOUNT_3.Level_No2 " & _
        '"        WHERE(dbo.ST_CHARTOFACCOUNT.Level_No = 1) " & _
        '" "
        sql = "select * from vw_alltree "

        'sql = " SELECT        Code, Name, MG_Item, G1_Item, G2_Item, PriceSal, PricePrcheses, Indusrty,Color,Size,CityName,NameCompny,Barcode_No FROM            dbo.VW_FINDDATAITEM2  WHERE        (Compny_Code = '" & VarCodeCompny & "') and Name Like '%" & Txt_NameItemFind.Text & "%' "

        'sql = "SELECT  code,name FROM  BD_ITEM   "
        rs = Cnn.Execute(sql)
        Dim da As OleDbDataAdapter = New OleDbDataAdapter(sql, con)
        'create a new dataset
        Dim ds As New DataSet()
        'fill the datset
        da.Fill(ds)
        GridControl4.DataSource = ds.Tables(0)
        ''GridColumn1.Caption = "d"
        GridView7.Columns(0).Caption = "اسم الحساب"
        GridView7.Columns(1).Caption = "المستوى 2"
        GridView7.Columns(2).Caption = "المستوى 3"
        GridView7.Columns(3).Caption = "المستوى 4"
        GridView7.Columns(4).Caption = "المستوى 5"
        GridView7.Columns(5).Caption = "نوع الحساب"
        GridView7.Columns(6).Caption = "طبيعة الحساب"


        'GridView1.Columns(7).Visible = False
        ''GridView1.Columns(8).Visible = False

        'GridView1.Columns(9).Visible = False
        ''GridView1.Columns(10).Visible = False
        ''GridView1.Columns(11).Visible = False
        'GridView1.Columns(12).Visible = False
        GridView7.Columns(0).GroupIndex = 1
        GridView7.Columns(1).GroupIndex = 2
        GridView7.Columns(2).GroupIndex = 3
        GridView7.Columns(3).GroupIndex = 4

        GridView7.ExpandAllGroups()

        'GridView7.Columns(1).AppearanceCell.BackColor = Color.DarkGray
        'GridView7.Columns(1).AppearanceCell.ForeColor = Color.Red

        'GridView7.Columns(2).AppearanceCell.BackColor = Color.Yellow
        'GridView7.Columns(2).AppearanceCell.ForeColor = Color.Black


        'GridView6.Columns(2).AppearanceCell.Font.FontFamily

        GridView7.Appearance.Row.Font = New Font(GridView7.Appearance.Row.Font, FontStyle.Bold)
        GridView7.Appearance.Row.Options.UseFont = True

        GridView7.BestFitColumns()


        ds = Nothing
        da = Nothing
        con.Close()
        con.Dispose()

    End Sub

    Sub Search3()
        On Error Resume Next


        GridControl4.DataSource = Nothing
        GridView7.Columns.Clear()

        'Dim con As New OleDb.OleDbConnection
        'Dim ss As String
        'ss = " Provider=OraOLEDB.Oracle;Data Source=test;User Id=" & varusername2 & ";Password=" & varPassword & ";"
        'con.ConnectionString = ss
        Dim ss As String
        Dim con As New OleDb.OleDbConnection
        ss = "Provider=SQLOLEDB;Initial Catalog= " & DatabaseName & " ;Data Source=" & ServerName & ";" & _
               "User ID=" & varusername2 & " ;Password=" & varPassword & ";"
        con.ConnectionString = ss
        con.Open()


        '   sql = "     SELECT        TOP (100) PERCENT RTRIM(dbo.Vw_PrintChart.AccountName) AS Levelname1, RTRIM(dbo.ST_CHARTOFACCOUNT.AccountNo_Name) AS LeveName2, RTRIM(ST_CHARTOFACCOUNT_1.AccountNo_Name) AS LevelName3,  " & _
        '"                         RTRIM(ST_CHARTOFACCOUNT_2.AccountNo_Name) AS levelName4, RTRIM(ST_CHARTOFACCOUNT_3.AccountNo_Name) AS levelName5, iif(dbo.ST_CHARTOFACCOUNT.AccountType=1,'ميزانية','قائمة دخل') as type, iif(dbo.ST_CHARTOFACCOUNT.AccountPh=1,'دائن','مدين') as typeacc " & _
        '" FROM            dbo.Vw_PrintChart INNER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT ON dbo.Vw_PrintChart.Account_No_Update = dbo.ST_CHARTOFACCOUNT.Level_No2 INNER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT AS ST_CHARTOFACCOUNT_1 ON dbo.ST_CHARTOFACCOUNT.Account_No = ST_CHARTOFACCOUNT_1.Level_No2 LEFT OUTER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT AS ST_CHARTOFACCOUNT_2 ON ST_CHARTOFACCOUNT_1.Account_No = ST_CHARTOFACCOUNT_2.Level_No2 LEFT OUTER JOIN " & _
        '"                         dbo.ST_CHARTOFACCOUNT AS ST_CHARTOFACCOUNT_3 ON ST_CHARTOFACCOUNT_2.Account_No = ST_CHARTOFACCOUNT_3.Level_No2 " & _
        '"        WHERE(dbo.ST_CHARTOFACCOUNT.Level_No = 1) " & _
        '" "
        sql = "select * from vw_alltree "

        'sql = " SELECT        Code, Name, MG_Item, G1_Item, G2_Item, PriceSal, PricePrcheses, Indusrty,Color,Size,CityName,NameCompny,Barcode_No FROM            dbo.VW_FINDDATAITEM2  WHERE        (Compny_Code = '" & VarCodeCompny & "') and Name Like '%" & Txt_NameItemFind.Text & "%' "

        'sql = "SELECT  code,name FROM  BD_ITEM   "
        rs = Cnn.Execute(sql)
        Dim da As OleDbDataAdapter = New OleDbDataAdapter(sql, con)
        'create a new dataset
        Dim ds As New DataSet()
        'fill the datset
        da.Fill(ds)
        GridControl4.DataSource = ds.Tables(0)
        ''GridColumn1.Caption = "d"
        GridView7.Columns(0).Caption = "اسم الحساب"
        GridView7.Columns(1).Caption = "المستوى 2"
        GridView7.Columns(2).Caption = "المستوى 3"
        GridView7.Columns(3).Caption = "المستوى 4"
        GridView7.Columns(4).Caption = "المستوى 5"
        GridView7.Columns(5).Caption = "نوع الحساب"
        GridView7.Columns(6).Caption = "طبيعة الحساب"


        'GridView1.Columns(7).Visible = False
        ''GridView1.Columns(8).Visible = False

        'GridView1.Columns(9).Visible = False
        ''GridView1.Columns(10).Visible = False
        ''GridView1.Columns(11).Visible = False
        'GridView1.Columns(12).Visible = False
        'GridView7.Columns(0).GroupIndex = 1
        'GridView7.Columns(1).GroupIndex = 2
        'GridView7.Columns(2).GroupIndex = 3
        'GridView7.Columns(3).GroupIndex = 4

        'GridView7.ExpandAllGroups()

        'GridView7.Columns(1).AppearanceCell.BackColor = Color.DarkGray
        'GridView7.Columns(1).AppearanceCell.ForeColor = Color.Red

        'GridView7.Columns(2).AppearanceCell.BackColor = Color.Yellow
        'GridView7.Columns(2).AppearanceCell.ForeColor = Color.Black


        'GridView6.Columns(2).AppearanceCell.Font.FontFamily

        GridView7.Appearance.Row.Font = New Font(GridView7.Appearance.Row.Font, FontStyle.Bold)
        GridView7.Appearance.Row.Options.UseFont = True

        GridView7.BestFitColumns()


        ds = Nothing
        da = Nothing
        con.Close()
        con.Dispose()

    End Sub
    Sub Search2()
        On Error Resume Next

        GridControl4.DataSource = Nothing
        GridView7.Columns.Clear()

        'Dim con As New OleDb.OleDbConnection
        'Dim ss As String
        'ss = " Provider=OraOLEDB.Oracle;Data Source=test;User Id=" & varusername2 & ";Password=" & varPassword & ";"
        'con.ConnectionString = ss
        Dim ss As String
        Dim con As New OleDb.OleDbConnection
        ss = "Provider=SQLOLEDB;Initial Catalog= " & DatabaseName & " ;Data Source=" & ServerName & ";" & _
               "User ID=" & varusername2 & " ;Password=" & varPassword & ";"
        con.ConnectionString = ss
        con.Open()


        sql = "select    Account_No_Update,AccountName from Vw_PrintChart "

        'sql = " SELECT        Code, Name, MG_Item, G1_Item, G2_Item, PriceSal, PricePrcheses, Indusrty,Color,Size,CityName,NameCompny,Barcode_No FROM            dbo.VW_FINDDATAITEM2  WHERE        (Compny_Code = '" & VarCodeCompny & "') and Name Like '%" & Txt_NameItemFind.Text & "%' "

        'sql = "SELECT  code,name FROM  BD_ITEM   "
        rs = Cnn.Execute(sql)
        Dim da As OleDbDataAdapter = New OleDbDataAdapter(sql, con)
        'create a new dataset
        Dim ds As New DataSet()
        'fill the datset
        da.Fill(ds)
        GridControl4.DataSource = ds.Tables(0)
        ''GridColumn1.Caption = "d"
        GridView7.Columns(0).Caption = "رقم الحساب"
        GridView7.Columns(1).Caption = "اسم الحساب"
       

        'GridView7.Columns(1).AppearanceCell.BackColor = Color.DarkGray
        'GridView7.Columns(1).AppearanceCell.ForeColor = Color.Red

        GridView7.Appearance.Row.Font = New Font(GridView7.Appearance.Row.Font, FontStyle.Bold)
        GridView7.Appearance.Row.Options.UseFont = True

        GridView7.BestFitColumns()


        ds = Nothing
        da = Nothing
        con.Close()
        con.Dispose()

    End Sub

    Private Sub Frm_ChartOfAccount_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        fill_GroupIncom()
        fill_Groupbalancesheet()
        fill_GroupcashFlow()
        Find_incomestatment()

        Search()

        com_typeacc1.Items.Add("مدين")
        com_typeacc1.Items.Add("دائن")

        com_typeacc2.Items.Add("مدين")
        com_typeacc2.Items.Add("دائن")

        com_typeacc3.Items.Add("مدين")
        com_typeacc3.Items.Add("دائن")
    End Sub


    Sub fill_GroupIncom()
        Com_Group_Item.Items.Clear()
        sql = "SELECT       rtrim(Name) as name FROM            dbo.TB_GroupIncome  where Compny_Code ='" & VarCodeCompny & "' "
        rs = Cnn.Execute(sql)
        Do While Not rs.EOF
            Com_Group_Item.Items.Add(rs("Name").Value)
            rs.MoveNext()
        Loop
    End Sub
    Sub fill_Groupbalancesheet()
        Com_Group_Item2.Items.Clear()
        sql = "SELECT    rtrim(Name) as name FROM            dbo.TB_GroupBalanceSheet  where Compny_Code ='" & VarCodeCompny & "' "
        rs = Cnn.Execute(sql)
        Do While Not rs.EOF
            Com_Group_Item2.Items.Add(rs("Name").Value)
            rs.MoveNext()
        Loop
    End Sub
    Sub fill_GroupcashFlow()
        Com_Group_Item3.Items.Clear()
        sql = "SELECT     rtrim(Name) as name FROM            dbo.TB_GroupCashFlow  where Compny_Code ='" & VarCodeCompny & "' "
        rs = Cnn.Execute(sql)
        Do While Not rs.EOF
            Com_Group_Item3.Items.Add(rs("Name").Value)
            rs.MoveNext()
        Loop
    End Sub


    Private Sub Cmd_New1_Click(sender As Object, e As EventArgs) Handles Cmd_New1.Click

        vartable = "TB_GroupIncome"
        Frm_GenralData.Close()
        'Frm_GenralData.MdiParent = Mainmune
        Frm_GenralData.Text = "بنود قائمة الدخل"
        Frm_GenralData.ShowDialog()
    End Sub

    Private Sub SimpleButton9_Click(sender As Object, e As EventArgs) Handles SimpleButton9.Click
        vartable = "TB_GroupBalanceSheet"
        Frm_GenralData.Close()
        'Frm_GenralData.MdiParent = Mainmune
        Frm_GenralData.Text = "بنود الميزانية"
        Frm_GenralData.ShowDialog()
    End Sub

    Private Sub SimpleButton13_Click(sender As Object, e As EventArgs) Handles SimpleButton13.Click
        vartable = "TB_GroupCashFlow"
        Frm_GenralData.Close()
        'Frm_GenralData.MdiParent = Mainmune
        Frm_GenralData.Text = "بنود قائمة الدخل"
        Frm_GenralData.ShowDialog()
    End Sub

    Private Sub Com_Group_Item_GotFocus(sender As Object, e As EventArgs) Handles Com_Group_Item.GotFocus
        fill_GroupIncom()
    End Sub

    Private Sub Com_Group_Item_SelectedIndexChanged(sender As Object, e As EventArgs) Handles Com_Group_Item.SelectedIndexChanged

    End Sub

    Private Sub Com_Group_Item2_GotFocus(sender As Object, e As EventArgs) Handles Com_Group_Item2.GotFocus
        fill_Groupbalancesheet()
    End Sub

    Private Sub Com_Group_Item2_SelectedIndexChanged(sender As Object, e As EventArgs) Handles Com_Group_Item2.SelectedIndexChanged

    End Sub

    Private Sub Com_Group_Item3_GotFocus(sender As Object, e As EventArgs) Handles Com_Group_Item3.GotFocus
        fill_GroupcashFlow()
    End Sub

    Private Sub Com_Group_Item3_SelectedIndexChanged(sender As Object, e As EventArgs) Handles Com_Group_Item3.SelectedIndexChanged

    End Sub

    Private Sub SimpleButton17_Click(sender As Object, e As EventArgs) Handles SimpleButton17.Click
        VARTBNAME = "vw_AccountData"
        varcode_form = 3001
        Frm_LookUpAccount.Fill_Acc()
        Frm_LookUpAccount.ShowDialog()
    End Sub

    Private Sub SimpleButton12_Click(sender As Object, e As EventArgs) Handles SimpleButton12.Click
        VARTBNAME = "vw_AccountData"
        varcode_form = 3002
        Frm_LookUpAccount.Fill_Acc()
        Frm_LookUpAccount.ShowDialog()
    End Sub

    Private Sub SimpleButton16_Click(sender As Object, e As EventArgs) Handles SimpleButton16.Click
        VARTBNAME = "vw_AccountData"
        varcode_form = 3003
        Frm_LookUpAccount.Fill_Acc()
        Frm_LookUpAccount.ShowDialog()
    End Sub

    Private Sub SimpleButton6_Click(sender As Object, e As EventArgs) Handles SimpleButton6.Click

        '============================رقم البند
        sql = "  SELECT *      FROM TB_GroupIncome  where Compny_Code = " & VarCodeCompny & " and name ='" & Com_Group_Item.Text & "'"
        rs = Cnn.Execute(sql)
        If rs.EOF = False Then varbandincome = rs("code").Value
        '=======================================


        sql = "Delete Tb_BandIncomeStatment  WHERE Compny_Code = " & VarCodeCompny & " and AccountNo ='" & txt_accno1.Text & "' and No_Band ='" & varbandincome & "'  "
        rs = Cnn.Execute(sql)

        MsgBox("تم الحذف", MsgBoxStyle.Information, "Css Solution Software Module")

        Find_incomestatment()
        txt_accno1.Text = ""
        txt_NameAccount1.Text = ""
    End Sub
    Sub Find_incomestatment()
        On Error Resume Next


        sql = "   SELECT        RTRIM(dbo.TB_GroupIncome.name) AS nameband, dbo.Tb_BandIncomeStatment.AccountNo, RTRIM(dbo.ST_CHARTOFACCOUNT.AccountName) AS accountName, iif(dbo.Tb_BandIncomeStatment.Type_Band=1,'مدين','دائن') as type " & _
               " FROM            dbo.Tb_BandIncomeStatment INNER JOIN " & _
               "                         dbo.TB_GroupIncome ON dbo.Tb_BandIncomeStatment.No_Band = dbo.TB_GroupIncome.code AND dbo.Tb_BandIncomeStatment.Compny_Code = dbo.TB_GroupIncome.Compny_Code INNER JOIN " & _
               "                         dbo.ST_CHARTOFACCOUNT ON dbo.Tb_BandIncomeStatment.AccountNo = dbo.ST_CHARTOFACCOUNT.Account_No AND dbo.Tb_BandIncomeStatment.Compny_Code = dbo.ST_CHARTOFACCOUNT.Compny_Code "

        Dim ss As String
        Dim con As New OleDb.OleDbConnection
        ss = "Provider=SQLOLEDB;Initial Catalog= " & DatabaseName & " ;Data Source=" & ServerName & ";" & _
               "User ID=" & varusername2 & " ;Password=" & varPassword & ";"
        con.ConnectionString = ss
        con.Open()

        rs = Cnn.Execute(sql)
        Dim da As OleDbDataAdapter = New OleDbDataAdapter(sql, con)
        'create a new dataset
        Dim ds As New DataSet()
        'fill the datset
        da.Fill(ds)
        GridControl1.DataSource = ds.Tables(0)
        GridView1.Columns(0).Caption = "أسم البند"
        GridView1.Columns(1).Caption = "رقم الحساب"
        GridView1.Columns(2).Caption = "أسم الحساب"
        GridView1.Columns(3).Caption = "نوع الحساب"
        GridView1.Appearance.Row.Font = New Font(GridView1.Appearance.Row.Font, FontStyle.Bold)
        GridView1.Appearance.Row.Options.UseFont = True
        GridView1.BestFitColumns()

        ds = Nothing
        da = Nothing
        con.Close()
        con.Dispose()


    End Sub
    Private Sub SimpleButton8_Click(sender As Object, e As EventArgs) Handles SimpleButton8.Click
        Dim sql2 As String

        If Len(txt_accno1.Text) = 0 Then MsgBox("من فضلك ادخل الحساب ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "Css Solution Software Module") : Exit Sub
        If Len(txt_AccName1.Text) = 0 Then MsgBox("من فضلك ادخل أسم الحساب ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "Css Solution Software Module") : Exit Sub

        '============================رقم البند
        sql = "  SELECT *      FROM TB_GroupIncome  where Compny_Code = " & VarCodeCompny & " and name ='" & Com_Group_Item.Text & "'"
        rs = Cnn.Execute(sql)
        If rs.EOF = False Then varbandincome = rs("code").Value
        '=======================================
        If com_typeacc1.Text = "مدين" Then vattypeband = 1
        If com_typeacc1.Text = "دائن" Then vattypeband = 2


        sql2 = "INSERT INTO Tb_BandIncomeStatment (No_Band, AccountNo,Type_Band,Compny_Code) " & _
          " values  ('" & varbandincome & "','" & txt_accno1.Text & "','" & vattypeband & "' ,'" & VarCodeCompny & "')"
        rs = Cnn.Execute(sql2)
        MsgBox("تم حفظ البيانات", MsgBoxStyle.Information + MsgBoxStyle.MsgBoxRight, "Css Solution Software Module")
        Find_incomestatment()
        txt_accno1.Text = ""
        txt_AccName1.Text = ""
    End Sub

    Private Sub SimpleButton11_Click(sender As Object, e As EventArgs) Handles SimpleButton11.Click
        Dim sql2 As String

        If Len(txt_accno2.Text) = 0 Then MsgBox("من فضلك ادخل الحساب ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "Css Solution Software Module") : Exit Sub
        If Len(txt_AccName2.Text) = 0 Then MsgBox("من فضلك ادخل أسم الحساب ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "Css Solution Software Module") : Exit Sub

        '============================رقم البند
        sql = "  SELECT *      FROM TB_GroupBalanceSheet  where Compny_Code = " & VarCodeCompny & " and name ='" & Com_Group_Item2.Text & "'"
        rs = Cnn.Execute(sql)
        If rs.EOF = False Then varbandbalancesheet = rs("code").Value
        '=======================================
        If com_typeacc2.Text = "مدين" Then vattypeband2 = 1
        If com_typeacc2.Text = "دائن" Then vattypeband2 = 2


        sql2 = "INSERT INTO St_SetupBox (No_Band, AccountNo,Type_Band,Compny_Code) " & _
          " values  ('" & varbandbalancesheet & "','" & txt_accno2.Text & "','" & vattypeband2 & "' ,'" & VarCodeCompny & "')"
        rs = Cnn.Execute(sql2)
        MsgBox("تم حفظ البيانات", MsgBoxStyle.Information + MsgBoxStyle.MsgBoxRight, "Css Solution Software Module")
        'Find()
        txt_accno2.Text = ""
        txt_AccName2.Text = ""
    End Sub

    Private Sub SimpleButton15_Click(sender As Object, e As EventArgs) Handles SimpleButton15.Click
        Dim sql2 As String

        If Len(txt_accno3.Text) = 0 Then MsgBox("من فضلك ادخل الحساب ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "Css Solution Software Module") : Exit Sub
        If Len(txt_AccName3.Text) = 0 Then MsgBox("من فضلك ادخل أسم الحساب ", MsgBoxStyle.Critical + MsgBoxStyle.MsgBoxRtlReading, "Css Solution Software Module") : Exit Sub

        '============================رقم البند
        sql = "  SELECT *      FROM TB_GroupCashFlow  where Compny_Code = " & VarCodeCompny & " and name ='" & Com_Group_Item3.Text & "'"
        rs = Cnn.Execute(sql)
        If rs.EOF = False Then varband_tdfkat = rs("code").Value
        '=======================================
        If com_typeacc3.Text = "مدين" Then vattypeband3 = 1
        If com_typeacc3.Text = "دائن" Then vattypeband3 = 2


        sql2 = "INSERT INTO St_SetupBox (No_Band, AccountNo,Type_Band,Compny_Code) " & _
          " values  ('" & varband_tdfkat & "','" & txt_accno3.Text & "','" & vattypeband3 & "' ,'" & VarCodeCompny & "')"
        rs = Cnn.Execute(sql2)
        MsgBox("تم حفظ البيانات", MsgBoxStyle.Information + MsgBoxStyle.MsgBoxRight, "Css Solution Software Module")
        'Find()
        txt_accno3.Text = ""
        txt_AccName3.Text = ""
    End Sub

    Private Sub SimpleButton18_Click(sender As Object, e As EventArgs) Handles SimpleButton18.Click
        Frm_Print_ChartofAccount.Show()
    End Sub

    Private Sub SimpleButton19_Click(sender As Object, e As EventArgs) Handles SimpleButton19.Click
        If OPTree.Checked = True Then Search()
        If OPStrat.Checked = True Then Search2()
        If OPTable.Checked = True Then Search3() : GridView7.BestFitColumns()


        GridView1.ExpandAllGroups()
    End Sub

    Private Sub Cmd_Print_Click(sender As Object, e As EventArgs) Handles Cmd_Print.Click
        GridView7.ShowRibbonPrintPreview()
    End Sub

    Private Sub txt_NameAccount2_TextChanged(sender As Object, e As EventArgs) Handles txt_NameAccount2.TextChanged

    End Sub
End Class